name: napa_widgets
description: "Napa widgets are an inspectable and serializable version of common Flutter widgets."
version: 0.3.0
repository: https://github.com/rusoleal/napa_widgets
topics:
  - reflection
  - serialization
  - ui

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0
  inspectable_property: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
